"""Initial_migration

Revision ID: 025c76d30ae3
Revises: 001
Create Date: 2026-01-08 10:46:18.390982+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025c76d30ae3'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'characters', ['id'])
    op.drop_constraint('scenes_name_key', 'scenes', type_='unique')
    op.create_unique_constraint(None, 'scenes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenes', type_='unique')
    op.create_unique_constraint('scenes_name_key', 'scenes', ['name'])
    op.drop_constraint(None, 'characters', type_='unique')
    # ### end Alembic commands ###
