"""add_image_column_to_character_and_scene

Revision ID: 897e43c89270
Revises: 025c76d30ae3
Create Date: 2026-01-24 09:51:32.983413+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897e43c89270'
down_revision = '025c76d30ae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('image', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'image')
    op.drop_column('characters', 'image')
    # ### end Alembic commands ###
