"""add_chats_example_to_characters

Revision ID: 570872883d4a
Revises: 897e43c89270
Create Date: 2026-01-25 09:43:06.324790+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '570872883d4a'
down_revision = '897e43c89270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('chats_example', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'chats_example')
    # ### end Alembic commands ###
